import { Inter } from "next/font/google";
import "./globals.css";
import styles from './layout.module.css';
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({title, keywords, description, children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <div className={styles.container}>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
